// Writes src/version.ts from package.json.
//
// The User-Agent used to be a literal in client.ts, beside a version that lives
// in package.json. That shape drifts: the Python SDK served 0.2.2 from PyPI while
// announcing 0.2.0 on the wire. Reading package.json at runtime is not an option
// worth taking -- it is deliberately absent from "exports", and adding it there to
// satisfy a header would widen the public surface -- so the value is baked in at
// build time from the one place it is declared.
//
// The generated file is committed so a plain `tsc` typechecks without a build
// step, and test/version.test.mjs fails if it has gone stale.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { version } = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

const body = `// GENERATED by scripts/gen-version.mjs -- do not edit.
// Regenerate with \`npm run build\`. Sourced from package.json.
export const VERSION = ${JSON.stringify(version)};
`;

const out = join(root, "src", "version.ts");
const previous = (() => {
  try {
    return readFileSync(out, "utf8");
  } catch {
    return null;
  }
})();

if (previous !== body) {
  writeFileSync(out, body);
  console.log(`gen-version: src/version.ts -> ${version}`);
} else {
  console.log(`gen-version: src/version.ts already at ${version}`);
}
